
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm5hbWUiOiJDYW50aWthIiwiZW1haWwiOiJhdXJlbEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImF1cmVsOCIsImlhdCI6MTczNjg2MTMwNSwiZXhwIjoxNzM2ODYxMzI1fQ.GRRaGrAIFKy-to4crrx5Xrc47tRGBuSlw70MwsU752I
###

POST http://localhost:5000/users/register
Content-Type: application/json

{
    "name": "Cantika",
    "username": "aurel8",
    "email": "aurel@gmail.com",
    "password": "password123",
    "confPassword": "password123"
}

###
POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "aurel@gmail.com",
    "password": "password123"
}

###
GET http://localhost:5000/token
Content-Type: application/json

###
DELETE http://localhost:5000/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obkBleGFtcGxlLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzM2NzU3Njg5LCJleHAiOjE3MzY4NDQwODl9.Iw2M9kU5m-OfV"
}

