

POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "Henry Jonathan",
    "username": "henryjonathnn",
    "email": "jonathan@gmail.com",
    "password": "12345678",
    "confPassword": "12345678"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "jonathan@gmail.com",
    "password": "12345678"
}

###
GET http://localhost:5000/users

###
GET http://localhost:5000/users/1

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Nala Dev",
    "username": "naladev",
    "email": "naladev@gmail.com",
    "password": "Nala_01"
}

###
PATCH http://localhost:5000/users/1
Content-Type: application/json

{
    "name": "Hyura Dev",
    "username": "hyuradev",
    "email": "hyuradev@gmail.com",
    "password": "Hyura_01"
}
###
DELETE http://localhost:5000/users/5